PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX td5: <http://www.utc.fr/> 
SELECT ?Person 
WHERE {
	td5:Paul foaf:topic_interest ?c1 .
	?Person foaf:topic_interest ?c2 .
	FILTER(?c1 = ?c2)
}